### ISSUE TITLE
Create Mapsui.Rendering.Uno to support Uno platform.

### ISSUE THREAD

**Issue by vkotov** [Mapsui/Mapsui#1109]
Is it possible to adapt Mapsui rendering subsystem to run on [Uno platform](http://platform.uno)?
On iOS, Android and macOS, the Uno Platform relies on the current Xamarin Native stack (not Xamarin.Forms). 
On WebAssembly, the Uno Platform relies directly on the Mono-WASM runtime, a part of.NET 5.
On Linux, Uno Platform relies on Skia to draw the UI on canvas.
Uno Platform acts a bridge for WinUI and UWP apps to run natively on iOS, macOS, Android, Linux and WebAssembly.
You can run your C# and XAML source code unmodified and compile it on a different platform yet have it behave the same at runtime.

**Comment by tmijieux** [comment]
I think it is possible
I dont think it is required to create a "Mapsui.**Rendering**.Uno , *rendering* is the is the part of mapsui library that does the rendering but it is mostly not exposed in the final usable controls used in the different frameworks, basically anywhere either skiasharp or "xaml renderer" can run, we do not need to create a new "rendering" namespace rather a new Mapsui.UI.Uno namespace.What need to be done, is implementing a partial class MapControl that inherits controls for the target framework .
Skiasharp already has views for uno [here](https://github.com/mono/SkiaSharp/tree/main/source/SkiaSharp.Views.Uno), so you need to take example on any of the Mapsui.UI.XXXX.MapControl class and subclass these views and that'll probably works...

**Comment by pauldendulk** [comment]
> I think it is possible
> I dont think it is required to create a "Mapsui.**Rendering**.Uno" , _rendering_ is the part of mapsui library that does the rendering but it is mostly not exposed in the final usable controls used in the different frameworks, basically anywhere either skiasharp or "xaml renderer" can run, we do not need to create a new "rendering" namespace rather a new Mapsui.UI.Uno namespace.
> 
> What need to be done, is implementing a partial class MapControl that inherits Views for the target framework .
> Skiasharp already has views for uno [here](https://github.com/mono/SkiaSharp/tree/main/source/SkiaSharp.Views.Uno), so you need to take example on any of the Mapsui.UI.XXXX.MapControl class and subclass these views and that'll probably works...

Yes, I assume that is correct. The Mapsui.Rendering.Skia is a .netstandard2.0 that I think can just be used as such in Mono WASM.

**Comment by FrozDark** [comment]
Mapsui uno needs to be possible to run on Uno WinUI instead of UWP version as it transits to WinUI 3

**Comment by inforithmics** [comment]
Wasm:
Currently Mapsui runs on Uno.Wasm. 

Mapsui.Rendering.Uno:
Mapsui.Rendering.Uno is not needed because Uno renders with SkiaSharp so the SkiaSharp Renderer of Mapsui works just fine in Uno.

Uno.WinUI:
Pull request: 
https://github.com/Mapsui/Mapsui/pull/1648

**Comment by FrozDark** [comment]
There is a missing class MapControl in appveyour builds on Mobile UNO Platform. Especialy I tried on Android

Java.Lang.ClassNotFoundException: crc6462b5399ce6dea9db.MapControl
 ---> Java.Lang.ClassNotFoundException: Didn't find class "crc6462b5399ce6dea9db.MapControl"

**Comment by inforithmics** [comment]
I looked into the nuget package and the class was there, so maybe a tooling issue. I will update write the GetStarted samples for Uno maybe I'll find there something.
Have you a reproduction Sample?

**Comment by FrozDark** [comment]
That error occurs in the debug. I'll attach a repro later

**Comment by FrozDark** [comment]
Here is the small repro of the issue
[DroidMapIssue.zip](https://github.com/Mapsui/Mapsui/files/9333773/DroidMapIssue.zip)

App fails on map init with the exception
![ujt3](https://user-images.githubusercontent.com/6670150/184547091-5929bc30-fe4a-41ba-8af6-00a82673eb46.jpg)

**Comment by inforithmics** [comment]
I'm currently writing the QuickStart for the mapsui.Uno and Visual Studio 17.3 brought so many changes, that I'm applying the 3rd workaround to only compile the map. (In newer Uno Versions (Dev) this is fixed. So you have to increase the Uno Version to the latest Dev versions. When offical Uno stable versions are released I will make a pull request for updating the dependencies. 

I haven't looked yet at your sample I guess that maybe the mapsui.Uno versions needs to target every supported target specifically (Android,ios, ....)

**Comment by inforithmics** [comment]
I can now reproduce the problem

**Comment by inforithmics** [comment]
Is fixed in this pull request you could try the created nuget packages

**Comment by FrozDark** [comment]
> Is fixed in this pull request #1695 you could try the created nuget packages

Is this included in 3880 build?
I tried 3880 but it still fails to run with missing class exception

**Comment by inforithmics** [comment]
Can you try this build? Because it's the first time that the appveyor build went through.

https://ci.appveyor.com/project/pauldendulk/mapsui/builds/44653168/artifacts

**Comment by FrozDark** [comment]
> Can you try this build? Because it's the first time that the appveyor build went through.
> 
> https://ci.appveyor.com/project/pauldendulk/mapsui/builds/44653168/artifacts
3909 works well. Thanks

**Comment by pauldendulk** [comment]
https://github.com/Mapsui/Mapsui/pull/1695 was merged.

**Comment by pauldendulk** [comment]
Uno and Uno.WinUI were added in v4.
