### ISSUE TITLE
Mapsui.Samples.Maui does not work properly on iOS (and Mac)

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#2087]
**Mapsui Version**
master as of today with modifications from PR https://github.com/Mapsui/Mapsui/pull/2084, which are necessary to restore the sln with VS4Mac (branch janusw:building_xamarin_forms_on_mac)

**Mapsui Platform**
MAUI

**Device**
iOS (iPhone + iPad), MacOS (MacBook Pro)

**Describe the bug**
When building and running the MAUI sample on iOS (or Mac), the app starts up alright and I can select a sample category via the picker, but when tapping on a specific sample name, nothing happens. No map is shown.

**Comment by pauldendulk** [comment]
I can reproduce this when running Mapsui.Samples.Maui Android on Windows Subsystem for Android.

**Comment by janusw** [comment]
> I can reproduce this when running Mapsui.Samples.Maui Android on Windows Subsystem for Android.

so you say that Android has the same issue as iOS and Mac, and you don't see #2088 on Windows?

**Comment by janusw** [comment]
> Fixed with #2087

Actually it is not fully fixed for me. The effect I see from #2087 is that now the sample name is highlighted when tapping on it. But on the iPhone and iPad I still see no map. The reason seems to be that the controls for selecting the sample are simply too large (and take up the whole screen on "small" devices - even on an 11" iPad).

When running the MAUI sample on MacOS, I see only a small map on the right side of the screen (see screenshot below), so at least the layout of the controls should be improved.

Note that in the Xamarin.Forms sample, the controls for selecting a sample are hidden when selecting a control and the map is shown almost full-screen (at least on Android and iOS - on Mac the sample list is shown permanently).

<img width="1685" alt="Screenshot 2023-06-25 at 10 15 55" src="https://github.com/Mapsui/Mapsui/assets/484108/4d61afb7-af02-4f1e-a364-3fba2c15731b">

**Comment by pauldendulk** [comment]
The behavior you describe on iOS and MacOS is indeed unacceptable. Thanks for the feedback. I will add further improvements. Probably by adding a flyout, like mentioned above.

**Comment by pauldendulk** [comment]
Fixed with https://github.com/Mapsui/Mapsui/pull/2199#pullrequestreview-1662726444

**Comment by janusw** [comment]
Thanks for fixing the layout. Looks pretty good on an iPad now (on a small iPhone, the layout is still not optimal in portrait mode, but that is bearable).

Btw, one other difference between the Maui sample and the Xamarin.Forms sample is that for Maui, the widget bar seems to be missing (i.e. the round widgets for zooming and centering), e.g. in Demo -> OpenStreetMap.

**Comment by pauldendulk** [comment]
@janusw I update the Maui MapControl sample, but there is also the Maui MapView sample which has a lot of shared code with Xamarin.Forms. That one should have the round buttons.

**Comment by janusw** [comment]
Thanks for the hint. I completely missed the fact that there is another variant of the Maui sample 🙈
