### ISSUE TITLE
Info broken in 1.4.1 for polygons

### ISSUE THREAD

**Issue by Kortdag** [Mapsui/Mapsui#417]
We did upgrade to Mapsui 1.4.1 yesterday to use the wmslockup fix. It worked great!! Great work!

Unfortunately there is a bug in the info tool that we really depend on - so we´re a bit stuck since going back to 1.3.1 is less attractive.

To reproduce use the default InfoSample an try the white polygon in the middle.
Did the test in WPF since its after work and I dont have all the Mac stuff at home..

Polygons are treated in the InfoHelper.cs in the last part

 else
            {
                
                return feature.Geometry.Distance(point) <= marginInWorldUnits;
            }

Lookes like a copy/paste from the line extension. Must be something like 
return feature.Geometry.Contains(point);

Did try that but also the WorldPosition is drasticly different between 1.3.1 and 1.4.1. Atleast on WPF, not sure on iOS - which is really my main focus

MousePosition:  POINT (369.116666666667 381.6)
GetMapInfo WorldPosition: POINT (-120954.373453544 21582.9365270251)

MousePosition: POINT (370.716666666667 377.6)
GetMapInfo WorldPosition: POINT (-4035199.77043415 4312270.71809985)

If its an easy fix what are the chances of an 1.4.1 fix? I can see that you busy with 2.0 but our releasedate is getting nearer :-). I know you do it in your spare time so just asking! If not possible I will possibly just add the source to our project and figure it out

**Comment by charlenni** [comment]
You say, that you have problems, but not what that problems are. I ask, because I tested it with 1.4 and found the normal behavior.

**Comment by Kortdag** [comment]
There is not feature info response when clicking the items.
map.Info += (sender, args) =>
            {
                Debug.WriteLine(args?.MapInfo?.Layer != null ? args.MapInfo.Layer.Name : "Nothing");
                Debug.WriteLine(args?.MapInfo?.Feature != null ? args.MapInfo.Feature.ToString() : "Nothing");
            };

I dont know if **1.4** is the same source as **1.4.1**. I just downloaded 1.4.1 again from 

https://github.com/Mapsui/Mapsui/releases  (.zip)

Build and ran the InfoSample using the WPF sample. If I click on e.g. the white polygon in the middle there is no hits. I face the same issue in our iOS project.

If you open the WPF sample in the default window size and click about a cm south of the southern tip of Madagascar and slightly to the right it shows "Click info polygon 1".

**Comment by pauldendulk** [comment]
I will try to take a look tomorrow morning.

**Comment by spaddlewit** [comment]
I'm having a similar problem, but with a point layer. I noticed the name of the event changed moving from Mapsui 1.3.x to 1.4.x, so I just renamed the event name, but it turns out it now isn't firing. I don't actually create an info layer though, I just have a regular point layer and calculate my own 'feature nearest to mouse click' when the event fires.

**Comment by pauldendulk** [comment]
I can not reproduce it in wpf. Not with the skia renderer and not with the wpf renderer. Perhaps it is related to the skia scale which is 1 most of the time, but was not 1 one at some point while developing (which allowed me to fix the white border bug). I have no idea why it was not 1 then, I am developing on the same laptop no, with no second screen. 

@Kortdag Do you have the same problem if you select the wpf renderer (top left dialog in the sample)?

**Comment by pauldendulk** [comment]
@spaddlewit On what platform did you test this?

**Comment by Kortdag** [comment]
Screen recording: Same for both WPF and SKia
[Repro.zip](https://github.com/Mapsui/Mapsui/files/2016046/Repro.zip)

**Comment by Kortdag** [comment]
Cloned repository.
Is this from the front page https://github.com/Mapsui/Mapsui 
I will try this.

**Comment by pauldendulk** [comment]
Interesting, i have never opened an .mht. Now downloading mht viewer from the windows store. What do you use to view it?

**Comment by pauldendulk** [comment]
it crashes. Perhaps just press the 'next' link in the browser.

**Comment by pauldendulk** [comment]
@Kortdag Do you get any feature info at any point if you click/hover randomly in the map?

**Comment by pauldendulk** [comment]
@Kortdag Do you have the latest windows update? (i have not)

**Comment by Kortdag** [comment]
Ahhh I actually didn´t look into the zip. I just googled Windows screen recorder and came up with PSR.exe. Thought it was a video. It opens in Explorer but its static screen shots. 

Will look into other options and test on the Master branch. Will get back ASAP, but new im just trying to fik framework versions since i dont have 4.7

**Comment by Kortdag** [comment]
It seems most shared libs tagergets netstandard 1.3 but nuget restores 1.6. Do you know which one I should use to be as close as possible?

**Comment by pauldendulk** [comment]
In this in master? There is a 1.4 branch which holds the code for the current 1.4.1 release.

**Comment by Kortdag** [comment]
I have upgrated VS2017 to support framework 4.7 and downloaded sources  from rebuild, run. Changed nothing.

Master:  https://github.com/Mapsui/Mapsui'
1.4.1: https://github.com/Mapsui/Mapsui/releases

Here is a video of what I see.
[Repro.zip](https://github.com/Mapsui/Mapsui/files/2016584/Repro.zip)


Notice that this morning I did not have .net framework. 4.7 only 4.6.1. It was possible to run 1.4.1 but not master. Master had some stuff in the Skia renderer. Value tuple something in the master that did not apprear in the 1.4.1. Maybe thats as expected?

**Comment by charlenni** [comment]
For the coordinates: at which resolution?

**Comment by pauldendulk** [comment]
Could you put a breakpoint on MapControlLoaded, _scale = GetScale();?

```c#
        private void MapControlLoaded(object sender, RoutedEventArgs e)
        {
            _scale = GetScale();
            TryInitializeViewport();
            UpdateSize();
            InitAnimation();
            Focusable = true;
        }
```
I hope the scale is not 1.

In wpf scale it goes wrong because after the dropdown select there should be another _scale = GetScale();

**Comment by Kortdag** [comment]
The same world point of course :-). 
Resolution should only matter for the mouse to world transformation but not the end result.

Look at the video and compare the mouse position in the map to the value written out in the InfoHelper. 
[Coordinate.zip](https://github.com/Mapsui/Mapsui/files/2016704/Coordinate.zip)

Its the same 1.4.1 mentioned above. 



[Coordinate.zip](https://github.com/Mapsui/Mapsui/files/2016691/Coordinate.zip)

**Comment by Kortdag** [comment]
In the WPF map control the scale is 1.25.

**Comment by pauldendulk** [comment]
Great. and I just realized I can just work with a fake scale (we set it in the renderer anyway) so this means I can solve this.

The iOS issue is a separate one I think. I will just apply the same logic there.

**Comment by Kortdag** [comment]
Excellent.  
iOS is my main concern so if the fix translate to iOS thats a great news.

**Comment by charlenni** [comment]
Regarding .Net 4.6.1 and the missing tupels: you could use the NuGet System.ValueTuples, because tupels are only standard from .Net 4.7 and higher.

**Comment by pauldendulk** [comment]
I have written something down about skia scale:
https://github.com/Mapsui/Mapsui/blob/master/docfx/mapsui/documentation/skia-scale.md

I rewrote Android and iOS a bit to be more in line with this. In iOS however there is no correction for the very last bullet. It only makes sense if this is needed there too. However, I can not test on iOS right now. The problem should be that when pinch zooming the center of the pinch does not correspond to the center of change on the map.

**Comment by Kortdag** [comment]
If I understand correctly in theory you expect it to work regarding info but asumess a problem with pinch zoom? But as you state cannot test it.

Im happy to help testing it on iOS. Im away for the weekend and will be back on work tuesday (where all Apple stuff is). 
Let me know if there is anything I can do then.

**Comment by Kortdag** [comment]
If I understand correctly in theory you expect it to work regarding info but asumess a problem with pinch zoom? But as you state cannot test it.

Im happy to help testing it on iOS. Im away for the weekend and will be back on work tuesday (where all Apple stuff is). 
Let me know if there is anything I can do then.

**Comment by pauldendulk** [comment]
yes, that is correct. 

I still have to properly correct wpf for skia scale.

**Comment by spaddlewit** [comment]
@pauldendulk I've confirmed -- this is iOS-only. Works fine in UWP.

**Comment by pauldendulk** [comment]
@spaddlewit Not really. Perhaps copy the MapControl to your own code and modify it. 

Did you test with the latest version of the code in the 1.4 branch or with the 1.4.1 nuget package?

**Comment by spaddlewit** [comment]
@pauldendulk I tested with the NuGet package. :(

**Comment by pauldendulk** [comment]
That was an old fix that solved problems for some but apparently introduced problems for others. 

My recent fixes were not pushed yet, so you could not test them, sorry about that. Here they are in the 1.4 branch:
https://github.com/Mapsui/Mapsui/commits/1.4

I tested Android, seems okay to me. 

iOS has the same logic as Android apart from the centering. I expect it to behave awkward there, but map info should be correct.

I am working on WPF right now.

**Comment by pauldendulk** [comment]
@Kortdag My most recent commit should fix the wpf info problem.

**Comment by spaddlewit** [comment]
@pauldendulk Will there be a 1.4.2? :) :) :)

**Comment by pauldendulk** [comment]
Yes.

**Comment by Kortdag** [comment]
Great with a 1.4.2. 
No to be "pushy" but do you have a rough estimate of when its planned. Like this week, next or unplanned?

Im asking because we about to release and we just need to decide weather to go back to 1.3.1, stay on 1.4.1 and try to implement a fix or upgrade to 1.4.2. 

I know its open source so it happens when people have the time etc. Basicly Im just looking for an intention and not a commitment, so we can choose between plan A, B og C :-).

**Comment by pauldendulk** [comment]
There is a 1.4.2-beta.1 out. If this fixes your problem I would suggest to go with that one. 

btw. I still see scale issues in wpf. It could a skiasharp bug.

**Comment by Kortdag** [comment]
Great I will try it out. I thought there was and iOS issue pending. 
I will try it out right away.

**Comment by pauldendulk** [comment]
There probably is but i`d like to have your feedback.

**Comment by Kortdag** [comment]
There is some issues. I made a recording of the app using 1.4.1 and 1.4.2.Beta 

Same code different Mapsui version.

There is something fishy going on with the map size. 

It does not scale to fit i 1.4.2.beta.
Mayby this is also why info is still offset? And the scalebar moved. Zooming seems to be ok around the pinch center but a little difficult to be sure since the map / tiles behaves "funny".






[1.4.2.beta_New.zip](https://github.com/Mapsui/Mapsui/files/2030295/1.4.2.beta_New.zip)

**Comment by spaddlewit** [comment]
I just shipped anyway and let my users whine at me. :D

I might roll back to 1.3.x, but I'm afraid of any new troubles that might introduce...

**Comment by pauldendulk** [comment]
I released 1.4.2-beta.2 with a fix for the wpf map size issue and uwp map info issue. I tested Android and it is still correct. I did not test iOS. 

Thanks for the screen recording. I probably introduced this bug when trying to move more code into the shared file. Tonight I've spend some more serious time on this scale thing. I hope to come up with a better and simpler solution soon.

**Comment by Kortdag** [comment]
I just testet on iOS with beta2. The map size issue remains. 
The good news is that pinch zoom seems to work as expected, so the theoretical or expected pinch zoom issue might not materialize - unless the scaling fix affects this.

**Comment by pauldendulk** [comment]
So, yesterday I spend more time investigating skia scaling and I learned that there is a differences between OpenGL backend (used in iOS) and bitmap backend (used everywhere else). So trying to fix iOS like Android was a bad idea. The solution it actually needs might be much simpler than what I have now. 

btw, If anyone has an old unused iOS devices lying around at the office you could send it to me. It will improve iOS quality :)

**Comment by Kortdag** [comment]
Thanks for info. 
I will let the client know about a iOS device. Only thing its a public government agency and I guess like in every parts of the world they are placed under scrutiny regarding spendig and hardware. I would assume that thay would like to but probably would have to go through all kinds of approval to ship a already bought device. I´m almost sure it cannot be done - unfortunately. But will look into it.

**Comment by Kortdag** [comment]
@spaddlewit. Personally I would have no problem doing it, but I already told my own company (private) that we should do it. Im kind against them beeing cheep since we already make them a lot of money and from a company perspective its pennies. 
If they won´t we could team op funding it from our own pocket - no problem.

**Comment by Kortdag** [comment]
My company could do this. They just need some sort of "bill" to register. 
@pauldendulk : Let me know what you think. We could exchange emails and figure out where to buy a used device and how to get it to you. Probably you know best how to do this in.... The Nederlands?

**Comment by pauldendulk** [comment]
ah, thanks for trying to help out guys! My e-mail is pauldendulk@gmail.com. I guess I should take a look at marktplaat.nl.

**Comment by pauldendulk** [comment]
@Kortdag @spaddlewit Just released 1.4.2-beta.3 which tested on the iPhone X emulator. Map size seems correct, Map info seems correct, pinch zoom behavior seems correct. Could you please test it?

**Comment by Kortdag** [comment]
Great news. 
I will test first thing monday morning since I dont have a Mac at home to compile the solition.
Looking forward to test it

**Comment by Kortdag** [comment]
Great news. 
I will test first thing monday morning since I dont have a Mac at home to compile the solition.
Looking forward to test it

**Comment by Kortdag** [comment]
Worked like a charm. Also fixed our retina screen hack for info placement. Thumbs up!!!
So we made our PRD release today.
@pauldendulk. I send an email regarding sponsoring an ipad. Feel free to look at it when you have the time.

**Comment by pauldendulk** [comment]
Great! I will look at your mail. Wanted to fix this first.
