### ISSUE TITLE
Mapsui 2.0 - Raster mbtiles appear blurred after panning

### ISSUE THREAD

**Issue by jinkhera** [Mapsui/Mapsui#555]
This relates to the latest 2.0 of the sdk(beta 9). The map is created using MBTilesSource and it works fine. One thing we noticed is that the tiles appear quite blurred after panning. This does not always happen but from the screenshots you will see what I mean. After panning you will see the screen has half-rendered tiles.

![screenshot_20181211-071354](https://user-images.githubusercontent.com/178561/49785028-08e37680-fd17-11e8-80f9-3b88cdee63b1.png)
![screenshot_20181211-071410](https://user-images.githubusercontent.com/178561/49785029-08e37680-fd17-11e8-8949-2f9148d69161.png)

**Comment by pauldendulk** [comment]
It looks like the map is only trying to load the tiles in the upper left corner. The TileLayer has a hierarchical way of fetching tiles. 'Higher' level tiles are loaded to have some default backdrop when panning and avoiding white areas. On the bottom and right you see the higher level tiles. They cover a bigger area. 

So my guess is that something goes wrong initializing the viewport size. This is usually caused by mixing-up device-independent-units with pixels.

**Comment by pauldendulk** [comment]
The images of your other report show a different pattern though
https://github.com/Mapsui/Mapsui/issues/551

**Comment by jinkhera** [comment]
It's an Android app and this is some of the code on setting up the MapControl

`mapControl.RotationLock = true;
mapControl.UnSnapRotationDegrees = 0;
mapControl.ReSnapRotationDegrees = 0;
mapControl.Map.CRS = "EPSG:3857";
mapControl.Map.Transformation = new MinimalTransformation();`

**Comment by charlenni** [comment]
@jinkhera You use the normal MapControl, not the Forms? Do you set your viewport size by your own? If you pan the part of the map, that is blurred into the top left corner, get than the quality better?

**Comment by jinkhera** [comment]
@charlenni It's the normal MapControl. 

If I do as you suggest there is no affect on the tiles.

I only set the Pan and Zoom limits.

`var mostZoomedIn = resolutions[resolutions.Count - 1];
_mapControl.Map.Limiter.ZoomLimits = new MinMax(mostZoomedIn, mostZoomedOut);

 _mapControl.Map.Limiter.PanLimits = new Mapsui.Geometries.BoundingBox(-20037328.150514967739582, -15547260.468415679410100, 20037697.721769899129868, 20037697.721769899129868);

 _mapControl.Map.Limiter.PanMode = PanMode.KeepViewportWithinExtents;`

**Comment by jinkhera** [comment]
@pauldendulk would the CRS have an impact? mapControl.Map.CRS= "EPSG:3857"

**Comment by pauldendulk** [comment]
I published 2.0.0-beta.11. Could you test it?

**Comment by pauldendulk** [comment]
I can't reproduce the problem with the default MbTiles sample on Android. 
I added a Refresh on touch-up, but not sure if this helps since I can not reproduce it.

If not our focus should be on reproducing it. Can you reproduce the sample with the default mbtiles sample?

**Comment by jinkhera** [comment]
I did some tests and it seems not fixed for Android. I'm going to revert to 1.4.8 for now as the quality of the rendering is quite important. 

As part of the test I used the mbtiles from our app in the sample app and still the same result.

**Comment by pauldendulk** [comment]
I would really like to reproduce the problem. So, some more questions.
- If you run the mbtiles sample of Mapsui on your device do you have the same problem?
- If you use the default mbtiles sample in your application do you have the same problem?
- Do you have the same problem in wpf? (you could copy your file over one of the mbtiles that are now embbeded resources in the samples)?

**Comment by pauldendulk** [comment]
Closing this as 'can't reproduce'. If anyone can help to reproduce this then let me know.

**Comment by johnpudd** [comment]
Hi @pauldendulk, 

I've been looking into this while @jinkhera is on holiday. It's a literal edge case... 

The issue arises when the user has reached the maximum zoom for a specific layer, and then pans.

The lower level tiles are not added to the cache due to the condition in RefreshData:
` if (Enabled && extent.GetArea() > 0 && _tileFetchDispatcher != null && MaxVisible > resolution && MinVisible < resolution)`

I propose the following alternative:
 if (Enabled && extent.GetArea() > 0 && _tileFetchDispatcher != null && MaxVisible >= resolution && MinVisible <= resolution)

I've prepared an update at [https://github.com/EastpointSoftware/Mapsui/blob/refresh-layer-data-at-min-or-max-res/Mapsui/Layers/TileLayer.cs](https://github.com/EastpointSoftware/Mapsui/blob/refresh-layer-data-at-min-or-max-res/Mapsui/Layers/TileLayer.cs)

Please let me know if that's ok, and I'll create a pull request.

Thanks

**Comment by pauldendulk** [comment]
I'll take a PR. This looks good. Even if this does not solve the problem it fixes a possible issue because the current code is not correct. Did you test if it affects your mbtiles layer?

I am trying to understand why this is a problem now because this seems to be very old code. Do you set Max/MinVisible on your layer explicitly? Or is this min/max resolution caused by the ViewportLimiter.

**Comment by pauldendulk** [comment]
Great!

There is a possibly related issue posted here. Does you fix solve this issue as well? https://github.com/Mapsui/Mapsui/issues/551

**Comment by johnpudd** [comment]
Hi @pauldendulk,
It looks like #551 is unrelated - but I’m not sure it’s a mapsui issue.
I have some thoughts and will post on that issue directly.
Thanks again!!

**Comment by pauldendulk** [comment]
Okay. So I'll close this one.
