### ISSUE TITLE
Zoomed event not trigger using MapView

### ISSUE THREAD

**Issue by xFoRdeX** [Mapsui/Mapsui#723]
I want trigger the "Zoomed" event, but when I click on the Zoom button, it does nothing and the event is not trigger.
I'm using mvvm so I create this : 
```
MapView.Behaviors.Add(
                  new Prism.Behaviors.EventToCommandBehavior()
                  {
                       EventName = "Zoomed",
                       Command = ZoomedCommand,
                       EventArgsConverter = new 
    Helpers.Converters.EventArgsConverters.MapZoomedEventArgsConverter()
                   }
                );
```
It doesn't if I'm using the event with Map.zoomed += ... too. 
Did it exist an other way too make an action when I zoom ?

**Comment by pauldendulk** [comment]
What I see in code is the MapView.Zoomed event is triggered by a HandlerZoomed which attached to the MapControl.Zoomed which is called from the private MapControl.OnZoomOut which is never called (so something is wrong) and also from the private MapControlOnZoomIn which called from OnDoubleTabbed. Not sure how this is supposed to work.

**Comment by pauldendulk** [comment]
Januari 8 2020 there was a commit which now calls OnZoomOut so I assume this is fixed.

**Comment by pauldendulk** [comment]
Should be fixed in 2.0.0-beta.31 and later.

**Comment by AndrewTavi** [comment]
Hi,
I'm using v2.0.3 and it still doesn't trigger the event. Any solution?
Thanks

**Comment by sylverbee** [comment]
Same problem on v3.0.2
