### ISSUE TITLE
Add 2 properties to POINT

### ISSUE THREAD

**Issue by holonsoft** [Mapsui/Mapsui#905]
Please consider to add Z as a 3rd coordinate part with new POINT(x, y, z) to add informational altitude infos to a point. It has no influence regarding drawing on a 2D coordinate space but would be helpful for further processing
Additionally would be great to have a "object TAG" property to add more internal infos to a point.

Thx in advanced
Christian

**Comment by radderz** [comment]
Hi Christian,

You can do this with any feature type that you add to the map,

```
                        var mapMarker = new Feature
                        {
                            Geometry = point,
                        };

                        mapMarker["Tag"] = new object();
```

You can have any number of dictionary values on the marker and they are of type object so can be anything.

Does this work for you?

Otherwise what do you mean by point? As you can't put a point on a map, that is only a reference to where it is. The point class is also not sealed, so you could extend it and add the Z dimension..

**Comment by holonsoft** [comment]
Hi,
thank you for this quick answer. The "TAG thing" is solved, thank you for your suggestion, I'll use it as suggested.

Regarding the POINT: yes it is not sealed. But if I extend it, it could be an issue with the license (LGPL). I have to use MapsUI for a commercial customer project, so I prefer to have an external lib on a "as it is" base. Forking it and extend it is technical no problem but then I miss further updates ;-)
I hope I could explain the problem.

Best regrads
Christian

**Comment by pauldendulk** [comment]
Our intention is to migrate Mapsui to MIT https://github.com/Mapsui/Mapsui/issues/301. This plan is two years old now and still not realized. Perhaps it should get high priority now that 2.0 is released. Part of the plan is to migrate to NTS, which has a Z coordinate built in. https://github.com/Mapsui/Mapsui/issues/506.

**Comment by pauldendulk** [comment]
I will close this issue because we will not change the current geometries. We will either use NTS or replace our geometries with something very basic of our own making. You can vote on feature-request issues with a thumps up. 

https://github.com/Mapsui/Mapsui/issues?q=is%3Aopen+label%3Afeature-request+sort%3Areactions-%2B1-desc
